# Generated by Django 3.1 on 2020-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('long_url', models.TextField()),
            ],
        ),
    ]
