# Generated by Django 3.1.1 on 2020-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='click_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
